# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from rpc.order.v1 import order_pb2 as order__pb2

GRPC_GENERATED_VERSION = "1.78.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in order_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class OrderServiceStub(object):
    def __init__(self, channel):
        self.CreateOrder = channel.unary_unary(
            "/order.v1.OrderService/CreateOrder",
            request_serializer=order__pb2.CreateOrderRequest.SerializeToString,
            response_deserializer=order__pb2.CreateOrderResponse.FromString,
            _registered_method=True,
        )
        self.GetOrder = channel.unary_unary(
            "/order.v1.OrderService/GetOrder",
            request_serializer=order__pb2.GetOrderRequest.SerializeToString,
            response_deserializer=order__pb2.GetOrderResponse.FromString,
            _registered_method=True,
        )
        self.ListOrders = channel.unary_unary(
            "/order.v1.OrderService/ListOrders",
            request_serializer=order__pb2.ListOrdersRequest.SerializeToString,
            response_deserializer=order__pb2.ListOrdersResponse.FromString,
            _registered_method=True,
        )
        self.UpdateOrderStatus = channel.unary_unary(
            "/order.v1.OrderService/UpdateOrderStatus",
            request_serializer=order__pb2.UpdateOrderStatusRequest.SerializeToString,
            response_deserializer=order__pb2.UpdateOrderStatusResponse.FromString,
            _registered_method=True,
        )


class OrderServiceServicer(object):
    async def CreateOrder(self, request, context):
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    async def GetOrder(self, request, context):
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    async def ListOrders(self, request, context):
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    async def UpdateOrderStatus(self, request, context):
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_OrderServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "CreateOrder": grpc.unary_unary_rpc_method_handler(
            servicer.CreateOrder,
            request_deserializer=order__pb2.CreateOrderRequest.FromString,
            response_serializer=order__pb2.CreateOrderResponse.SerializeToString,
        ),
        "GetOrder": grpc.unary_unary_rpc_method_handler(
            servicer.GetOrder,
            request_deserializer=order__pb2.GetOrderRequest.FromString,
            response_serializer=order__pb2.GetOrderResponse.SerializeToString,
        ),
        "ListOrders": grpc.unary_unary_rpc_method_handler(
            servicer.ListOrders,
            request_deserializer=order__pb2.ListOrdersRequest.FromString,
            response_serializer=order__pb2.ListOrdersResponse.SerializeToString,
        ),
        "UpdateOrderStatus": grpc.unary_unary_rpc_method_handler(
            servicer.UpdateOrderStatus,
            request_deserializer=order__pb2.UpdateOrderStatusRequest.FromString,
            response_serializer=order__pb2.UpdateOrderStatusResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "order.v1.OrderService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("order.v1.OrderService", rpc_method_handlers)
